services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      - DATABASE_URL=postgresql+asyncpg://${PG_NAME}:${PG_PASSWORD}@db:5432/${PG_DB_NAME}
    command: >
      sh -c "./wait-for-it.sh db:5432 -- alembic revision --autogenerate -m 'Initial' && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
